name: Validate JSONs

on: push

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Validate JSON with Glob and Formats
        uses: ubik2/validate-json-action@0.1.3
        with:
          schema: /tasks/schema/schema.json
          json: /tasks/activity_set_step_goal.json
